GET http://localhost:3001/api/users/

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "yaroslav",
    "name": "Yaroslav Romashko",
    "password": "123"
}

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "ruslan",
    "name": "Ruslan Ivanov",
    "password": "123"
}

###

POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "Georgii",
    "password": "dfk"
}

###

GET http://localhost:3001/api/blogs/

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhcm9zbGF2IiwiaWQiOiI2NWU5ZTA3ZDk3ZmZkY2QzZTEwMzEzOWYiLCJpYXQiOjE3MDk4OTI2ODUsImV4cCI6MTcwOTg5NjI4NX0.3uqhQd1-Ie3azGbrQmceguB9ie7o73DKZtThnsJac_c

{
    "title": "My second blog with users connection",
    "author": "Me Uhgd",
    "_url": "http.www",
    "likes": "",
    "userId": "65e9e07d97ffdcd3e103139f"
}

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhcm9zbGF2IiwiaWQiOiI2NWU5ZTA3ZDk3ZmZkY2QzZTEwMzEzOWYiLCJpYXQiOjE3MDk4OTI2ODUsImV4cCI6MTcwOTg5NjI4NX0.3uqhQd1-Ie3azGbrQmceguB9ie7o73DKZtThnsJac_c

{
    "title": "My second blog with users connection",
    "author": "Me Uhgd",
    "_url": "http.www",
    "likes": ""
}

###

DELETE http://localhost:3001/api/blogs/65c225a0c5443cc038b5e5a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikdlb3JnaWkiLCJpZCI6IjY1YzIyMWY5M2Y2ZTExZjBjNDYxYmEwNyIsImlhdCI6MTcwNzI0MjE3MiwiZXhwIjoxNzA3MjQ1NzcyfQ.IA906wkukzj0KMkugUA_1fMuK2luT6GRMsq9TRythaM
