GET http://localhost:3001/api/users/

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "Georgii",
    "name": "Georgii Romashko",
    "password": "dfk"
}

###

POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "Georgii",
    "password": "dfk"
}

###

GET http://localhost:3001/api/blogs/

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikdlb3JnaWkiLCJpZCI6IjY1YzIyMWY5M2Y2ZTExZjBjNDYxYmEwNyIsImlhdCI6MTcwNzIyOTEwNCwiZXhwIjoxNzA3MjMyNzA0fQ.8YHLyI7O8fOjzHQhszhPOnRosEFiuphNEtRzQcbCMpA

{
    "title": "Hello3",
    "author": "Morgan3",
    "_url": "ghnfghnfghnf",
    "likes": "34"
}

###

DELETE http://localhost:3001/api/blogs/65bd03e57d035dc5ba98ec07